### ISSUE TITLE
Coordinate on whether it makes sense to add some overhead and setup org in GitHub, DAO + multi-sig etc

### ISSUE THREAD

**Issue by jjperezaguinaga** [ETHPoster/poster#11]

**Comment by auryn-macmillan** [comment]
Made a github org
https://github.com/ETHPoster

**Comment by auryn-macmillan** [comment]
I don't think we have any immediate need for a multi-sig or a DAO, but happy to set that up if/when it's necessary.

**Comment by jjperezaguinaga** [comment]
Sweet, let's keep it simple for now. Migrated already the front-end to ETHPoster and created a [PR](https://github.com/ETHPoster/contract/pull/14) for adding the temporary changes into the codebase. Happy to just have it as a separate branch or even as a PR while I clean things over.

No further work to do here.
