### ISSUE TITLE
Grant Fleek org access to deploy site

### ISSUE THREAD

**Issue by jjperezaguinaga** [ETHPoster/poster#26]
Probably the only integration we'll need, but albeit a good one for previewing the PRs and deploying the site. As I've transferred the repo, I no longer can deploy it from my personal account.

**Comment by auryn-macmillan** [comment]
You have admin access on the repo now

**Comment by jjperezaguinaga** [comment]
Can confirm #31 is being deployed to Fleek, closing, thanks!
